# Generated by Django 3.1.7 on 2021-06-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210616_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='parent',
        ),
    ]
